{
 "title": "http_loadshedding",
 "description": "HTTP Load Metrics",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "application",
    "query": {
     "query": "label_values(http_requests_concurrency_limit_total,job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(http_requests_concurrency_limit_total,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Concurrency Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(http_requests_concurrency_items_total{job=\"$application\", instance=~\"$instance\"}) / sum(http_requests_concurrency_limit_total{job=\"$application\", instance=~\"$instance\"}))",
     "legendFormat": "Concurrency Usage"
    }
   ]
  },
  {
   "title": "Queue Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(http_requests_queue_items_total{job=\"$application\", instance=~\"$instance\"}) / sum(http_requests_queue_limit_total{job=\"$application\", instance=~\"$instance\"}))",
     "legendFormat": "Concurrency Usage"
    }
   ]
  },
  {
   "title": "Task Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_task_processing_time_seconds_count{job=\"$application\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Concurrency Usage"
    }
   ]
  },
  {
   "title": "Task Latency (Avg)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_task_processing_time_seconds_sum{job=\"$application\", instance=~\"$instance\"}[$__rate_interval])) / (sum(rate(http_requests_task_processing_time_seconds_count{job=\"$application\", instance=~\"$instance\"}[$__rate_interval])))) > 0",
     "legendFormat": "Concurrency Usage"
    }
   ]
  },
  {
   "title": "Rejection Rate",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_rejected_total{job=\"$application\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Concurrency Usage"
    }
   ]
  },
  {
   "title": "Concurrency Limit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_concurrency_limit_total{job=\"$application\", instance=~\"$instance\"})",
     "legendFormat": "Concurrency Usage"
    }
   ]
  },
  {
   "title": "Queue Limit",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_queue_limit_total{job=\"$application\", instance=~\"$instance\"})",
     "legendFormat": "Concurrency Usage"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Concurrency Usage / Priority",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_concurrency_items_total{job=\"$application\", instance=~\"$instance\"}) by (job, priority)",
     "legendFormat": "Priority: {{priority}}"
    }
   ]
  },
  {
   "title": "Queue Usage / Priority",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_queue_items_total{job=\"$application\", instance=~\"$instance\"}) by (job,priority)",
     "legendFormat": "Priority: {{priority}}"
    }
   ]
  },
  {
   "title": "Task Execution / Second (Success)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_task_processing_time_seconds_count{job=\"$application\", instance=~\"$instance\"}[$__rate_interval])) by (method, priority)",
     "legendFormat": "{{method}} {{priority}}"
    }
   ]
  },
  {
   "title": "Concurrency Usage / Instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(sum(http_requests_concurrency_items_total{job=\"$application\", instance=~\"$instance\"}) by (job, instance)) / sum(http_requests_concurrency_limit_total{job=\"$application\", instance=~\"$instance\"}) by (job, instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Concurrency Usage Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_concurrency_limit_total{job=\"$application\", instance=~\"$instance\"}) by (job)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(http_requests_concurrency_items_total{job=\"$application\", instance=~\"$instance\"}) by (job)",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Queue Usage Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_requests_queue_limit_total{job=\"$application\", instance=~\"$instance\"}) by (job)",
     "legendFormat": "Limit"
    },
    {
     "expr": "sum(http_requests_queue_items_total{job=\"$application\", instance=~\"$instance\"}) by (job)",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Rejection Rate / Priority",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_rejected_total{job=\"$application\", instance=~\"$instance\"}[$__rate_interval])) by (priority, method)",
     "legendFormat": "{{method}} - {{priority}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"$application\", instance=~\"$instance\"}[30s]) * 100) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Task Execution Time - P50",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_requests_task_processing_time_seconds_bucket{job=\"$application\", instance=~\"$instance\"}[$__rate_interval])) by (le, priority))",
     "legendFormat": "{{method}} {{priority}}"
    }
   ]
  },
  {
   "title": "Task Execution Time - P90",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_requests_task_processing_time_seconds_bucket{job=\"$application\", instance=~\"$instance\"}[$__rate_interval])) by (le, priority))",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  {
   "title": "Task Execution Time - P99",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_requests_task_processing_time_seconds_bucket{job=\"$application\", instance=~\"$instance\"}[$__rate_interval])) by (le, priority))",
     "legendFormat": "{{method}} {{priority}}"
    }
   ]
  },
  {
   "title": "Queue Time P50",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_requests_queue_time_seconds_bucket{job=\"$application\", instance=~\"$instance\"}[$__rate_interval])) by (le, priority))",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  {
   "title": "Queue Time P90",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_requests_queue_time_seconds_bucket{job=\"$application\", instance=~\"$instance\"}[$__rate_interval])) by (le, priority))",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  {
   "title": "Queue Time P99",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 27 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_requests_queue_time_seconds_bucket{job=\"$application\", instance=~\"$instance\"}[$__rate_interval])) by (le, priority))",
     "legendFormat": "Priority {{priority}}"
    }
   ]
  }
 ]
}